# Generated by Django 2.2.3 on 2019-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190924_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Maggi',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Maggi')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Patties',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Patties')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBites',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/QuickBites')),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/Sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='SouthIndian',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='media/images/SouthIndian')),
            ],
        ),
    ]
