# Generated by Django 2.2.3 on 2019-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_beverage_chat_maggi_pasta_patties_pizza_quickbites_sandwich_southindian'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('original_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='images/menucard')),
            ],
        ),
        migrations.DeleteModel(
            name='Beverage',
        ),
        migrations.DeleteModel(
            name='Burger',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Maggi',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Patties',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='QuickBites',
        ),
        migrations.DeleteModel(
            name='Sandwich',
        ),
        migrations.DeleteModel(
            name='SouthIndian',
        ),
    ]
