# Generated by Django 2.2.3 on 2019-09-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190924_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCard',
            new_name='Menu',
        ),
    ]
