# Generated by Django 2.2.3 on 2019-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190924_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_ratings', models.IntegerField(default=2.5)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
