# Generated by Django 2.2.3 on 2019-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menu_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='product_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
