# Generated by Django 2.2.3 on 2019-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20191003_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='product_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
